name: Depup
on:
  schedule:
    - cron: "14 14 * * *" # Runs at 14:14 UTC every day
  repository_dispatch:
    types: [depup]

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-depup@v1
        id: depup
        with:
          file: Dockerfile
          version_name: BUMP_VERSION
          repo: haya14busa/bump

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore(deps): update bump to ${{ steps.depup.outputs.latest }}"
          commit-message: "chore(deps): update bump to ${{ steps.depup.outputs.latest }}"
          body: |
            Update bump to [v${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/releases/tag/v${{ steps.depup.outputs.latest }})
            Compare [v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }}](https://github.com/${{ steps.depup.outputs.repo }}/compare/v${{ steps.depup.outputs.current }}...v${{ steps.depup.outputs.latest }})
            This PR is auto generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3Adepup).
          branch: depup/bump
          base: main
          labels: "bump:minor"
